<?php

$tags = array(
    "administrative divisions",
    "administratives boundaries",
    "aerial photography",
    "air photo",
    "boundaries",
    "buildings",
    "buildings and structures",
    "cartography",
    "communications",
    "contours",
    "cultural features",
    "earth sciences",
    "electricity",
    "energy",
    "gcp",
    "geographic data",
    "geographic information systems",
    "geographical maps",
    "geography",
    "geomatics",
    "geophysics",
    "ground control points",
    "hydrography",
    "hypsography",
    "imagery and basemaps",
    "indian reserves",
    "industrial and commercial areas",
    "isolated communities",
    "lakes",
    "land cover",
    "land management",
    "landforms",
    "magnetic surveys",
    "maps",
    "photography",
    "pipelines",
    "places of interest",
    "relief and landforms",
    "rivers - streams",
    "terrain elevation",
    "topographical maps",
    "topographical relief",
    "topography",
    "toponymy",
    "toponymy - place names",
    "transportation",
    "vegetation",
    "vegetation cover",
    "water saturated soils",
    "wetlands");
